apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: worker
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dashboard-coordinator
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  